export declare const setRoomUrl: (url: string) => any;
export declare const setRoomState: (state: string) => any;
export declare const setRoomActiveSpeaker: (peerId: string) => any;
export declare const setRoomStatsPeerId: (peerId: string) => any;
export declare const setRoomFaceDetection: (flag: boolean) => any;
export declare const setMe: ({ peerId, displayName, displayNameSet, device }: {
    peerId: string;
    displayName: string;
    displayNameSet: boolean;
    device: any;
}) => any;
export declare const setMediaCapabilities: ({ canSendMic, canSendWebcam }: {
    canSendMic: boolean;
    canSendWebcam: boolean;
}) => any;
export declare const setCanChangeWebcam: (flag: boolean) => any;
export declare const setDisplayName: (displayName: string) => any;
export declare const setAudioOnlyState: (enabled: boolean) => any;
export declare const setAudioOnlyInProgress: (flag: boolean) => any;
export declare const setAudioMutedState: (enabled: boolean) => any;
export declare const setRestartIceInProgress: (flag: boolean) => any;
export declare const addProducer: (producer: any) => any;
export declare const removeProducer: (producerId: string) => any;
export declare const setProducerPaused: (producerId: string) => any;
export declare const setProducerResumed: (producerId: string) => any;
export declare const setProducerTrack: (producerId: string, track: any) => any;
export declare const setProducerScore: (producerId: any, score: number) => any;
export declare const addDataProducer: (dataProducer: any) => any;
export declare const removeDataProducer: (dataProducerId: string) => any;
export declare const setWebcamInProgress: (flag: boolean) => any;
export declare const setShareInProgress: (flag: boolean) => any;
export declare const addPeer: (peer: any) => any;
export declare const removePeer: (peerId: string) => any;
export declare const setPeerDisplayName: (displayName: string, peerId: string) => any;
export declare const addConsumer: (consumer: any, peerId: string) => any;
export declare const removeConsumer: (consumerId: string, peerId: string) => any;
export declare const setConsumerPaused: (consumerId: string, originator: string) => any;
export declare const setConsumerResumed: (consumerId: string, originator: string) => any;
export declare const setConsumerCurrentLayers: (consumerId: string, spatialLayer: number, temporalLayer: number) => any;
export declare const setConsumerPreferredLayers: (consumerId: string, spatialLayer: number, temporalLayer: number) => any;
export declare const setConsumerPriority: (consumerId: string, priority: number) => any;
export declare const setConsumerTrack: (consumerId: string, track: any) => any;
export declare const setConsumerScore: (consumerId: string, score: number) => any;
export declare const addDataConsumer: (dataConsumer: any, peerId: string) => any;
export declare const removeDataConsumer: (dataConsumerId: string, peerId: string) => any;
export declare const addNotification: (notification: any) => any;
export declare const removeNotification: (notificationId: string) => any;
export declare const removeAllNotifications: () => any;
//# sourceMappingURL=stateActions.d.ts.map